#' Summary plots of an animal's tracked path
#'
#' This function produces a summary plot of cumulative distance and velocity
#' over time, and rose plots of absolute and relative bearings, based on a list
#' object generated by the \code{trackPath} function.
#' @param path.list a list object created by the \code{trackPath} function
#' @details \code{plotSummary} uses \code{ggplot2} and \code{gridExtra} to
#'   produce a four panel summary plot.
#' @return A four panel summary plot.
#' @importFrom ggplot2 aes geom_line geom_histogram coord_polar ggplot
#'   scale_x_continuous theme_bw scale_fill_brewer
#' @importFrom gridExtra grid.arrange
#' @export
plotSummary = function(path.list) {
  ..count.. = NULL

  dat = as.data.frame(path.list$movement)
  cumDistance = cumsum(ifelse(is.na(dat$distance), 0, dat$distance)) + dat$distance * 0

  plot1 = ggplot2::ggplot(dat, ggplot2::aes(x = dat$time, y = dat$cumDistance)) +
    ggplot2::geom_line(color = "grey25") +
    ggplot2::theme_bw() +
    xlab("") +
    ylab("Distance (mm)") +
    ggplot2::ggtitle("Cumulative distance")

  plot2 = ggplot2::ggplot(dat, ggplot2::aes(x = dat$time, y = dat$velocity)) +
    ggplot2::geom_line(color = "grey85") +
    ggplot2::geom_line(ggplot2::aes(x = dat$time, y = movingAverage(dat$velocity, n = 13, centered = TRUE)), color = "grey25") +
    ggplot2::theme_bw() +
    xlab("Time (s)") +
    ylab("Velocity (mm/s)") +
    ggplot2::ggtitle("Velocity")

  dat = subset(dat, 'distance' != 0)

  plot3 = ggplot2::ggplot(dat, ggplot2::aes(x = dat$abs.angle)) +
    ggplot2::geom_histogram(ggplot2::aes(y = ..count../sum(..count..)), breaks = seq(0, 360, 15)) +
    ggplot2::coord_polar(start = 0) +
    ggplot2::theme_bw() +
    ggplot2::scale_fill_brewer() +
    ylab("Proportion") +
    ggplot2::ggtitle("Absolute bearing") +
    ggplot2::scale_x_continuous("", limits = c(0, 360), breaks = seq(0, 359, 45), labels = seq(0, 359, 45))

  plot4 = ggplot(dat, ggplot2::aes(x = dat$rel.angle)) +
    ggplot2::geom_histogram(ggplot2::aes(y = ..count../sum(..count..)), breaks = seq(-180, 180, 15)) +
    ggplot2::coord_polar(start = pi) +
    ggplot2::theme_bw() +
    ggplot2::scale_fill_brewer() +
    ylab("Proportion") +
    ggplot2::ggtitle("Relative turn direction") +
    ggplot2::scale_x_continuous("", limits = c(-180, 180), breaks = seq(-180, 180, 45), labels = seq(-180, 180, 45))

  gridExtra::grid.arrange(plot1, plot3, plot2, plot4, ncol = 2)

}
